### ISSUE TITLE
Project Name

### ISSUE THREAD

**Issue by yooperjb** [yooperjb/group-project#4]
Once we get a project we need a fancy name. Webprinc3ss to the rescue.

**Comment by webprinc3ss** [comment]
Maybe "Living Room"  or "Read 'n' Play".  Will think a bit more on this.

**Comment by yooperjb** [comment]
"The Living Room" 
"A place to entertain the bored."

**Comment by webprinc3ss** [comment]
How about "Bored No More" ?

**Comment by yooperjb** [comment]
I like it!
